parameters:
    sidus_eav_bootstrap.twig.extension.class: Sidus\EAVBootstrapBundle\Twig\SidusTwigExtension

services:
    sidus_eav_bootstrap.twig.extension:
        class: %sidus_eav_bootstrap.twig.extension.class%
        arguments: [@sidus_eav_model.family_configuration.handler]
        tags:
            - { name: 'twig.extension' }

    # Support for Symfony 2.8 : MopaBootstrapBundle doesn't use the alias for the tab type anymore
    sidus_eav_bootstrap.form.tab.type:
        parent: mopa_bootstrap.form.type.tab
        tags:
            - { name: form.type, alias: tab }
