parameters:
    mopa_bootstrap.form.type_extension.tabbed.class: Sidus\EAVBootstrapBundle\Form\Extension\TabbedFormTypeExtension

services:
    sidus_eav_bootstrap.form.type.tabbed_data:
        class: Sidus\EAVBootstrapBundle\Form\Type\TabbedDataType
        parent: sidus_eav_model.form.type.data
        calls:
            - [setTranslator, ['@translator']]
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.autocomplete_data_selector:
        class: Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
        arguments:
            - '@router'
            - '@sidus_eav_bootstrap.form.helper.compute_label'
            - '@doctrine'
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.combo_data_selector:
        class: Sidus\EAVBootstrapBundle\Form\Type\ComboDataSelectorType
        arguments:
            - '@sidus_eav_model.family.registry'
            - '@router'
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.helper.compute_label:
        class: Sidus\EAVBootstrapBundle\Form\Helper\ComputeLabelHelper
        arguments:
            - '@property_accessor'
