parameters:
    mopa_bootstrap.form.type_extension.tabbed.class: Sidus\EAVBootstrapBundle\Form\Extension\TabbedFormTypeExtension

services:
    sidus_eav_bootstrap.form.type.tabbed_data:
        class: Sidus\EAVBootstrapBundle\Form\Type\TabbedDataType
        parent: sidus_eav_model.form.type.data
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.autocomplete_data_selector:
        class: Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
        arguments:
            - '%sidus_eav_model.entity.data.class%'
            - '@doctrine'
            - '@sidus_eav_model.family_configuration.handler'
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.combo_data_selector:
        class: Sidus\EAVBootstrapBundle\Form\Type\ComboDataSelectorType
        arguments: ['@sidus_eav_model.family_configuration.handler']
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.sidus_bootstrap_collection:
        class: Sidus\EAVBootstrapBundle\Form\Type\BootstrapCollectionType
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.sidus_date_picker:
        class: Sidus\EAVBootstrapBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.sidus_datetime_picker:
        class: Sidus\EAVBootstrapBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.type.sidus_wysiwyg:
        class: Sidus\EAVBootstrapBundle\Form\Type\WysiwygType
        tags:
            - { name: form.type }

    sidus_eav_bootstrap.form.switch.type:
        class: Sidus\EAVBootstrapBundle\Form\Type\SwitchType
        tags:
            - { name: form.type }
