services:
    sidus_eav_bootstrap.twig.extension:
        class: Sidus\EAVBootstrapBundle\Twig\SidusTwigExtension
        arguments: ['@sidus_eav_model.family_configuration.handler', '@translator']
        tags:
            - { name: twig.extension }

